name: build
dependencies:
- mkl=11.3.3=0
- numpy=1.11.0=py35_1
- openssl=1.0.2h=0
- pip=8.1.1=py35_1
- python=3.5.1=0
- readline=6.2=2
- setuptools=20.7.0=py35_0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - py==1.4.31
  - pytest==2.9.1

